name: Build Release Apk

on:
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-24.04    
    steps:
    - name: Checkout Repo
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Install dependencies
      run: sudo apt-get install -y ninja-build
      
    - name: Build SoH
      run: |
        ./gradlew assembleRelease
        mv app/build/outputs/apk/release/app-release.apk soh.apk
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: soh-apk
        path: soh.apk
